# Generated by Django 5.2.7 on 2025-10-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(max_length=500)),
                (
                    "university",
                    models.CharField(
                        choices=[
                            ("NYU", "New York University"),
                            ("Columbia", "Columbia University"),
                            ("Fordham", "Fordham University"),
                            ("CUNY", "City University of New York"),
                            ("Pace", "Pace University"),
                            ("The New School", "The New School"),
                        ],
                        max_length=100,
                    ),
                ),
                ("profile_photo", models.ImageField(upload_to="profile_photos/")),
                ("visibility", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
