# Generated by Django 5.2.7 on 2025-10-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_drinking_preference_profile_eating_habit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="drinking_preference",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="eating_habit",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sharing_preference",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="smoking_preference",
        ),
    ]
