# Generated by Django 5.2.7 on 2025-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_drinking_preference_profile_eating_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="sharing_preference",
            field=models.CharField(
                choices=[
                    ("sharing", "Open to Sharing"),
                    ("non_sharing", "Prefer Not to Share"),
                    ("no_preference", "No Preference"),
                ],
                default="no_preference",
                max_length=20,
                verbose_name="Sharing Preference",
            ),
        ),
    ]
