# Generated by Django 5.2.7 on 2025-10-22 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_sharing_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="budget_max",
            field=models.IntegerField(
                default=5000, verbose_name="Maximum Monthly Budget ($)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="budget_min",
            field=models.IntegerField(
                default=0, verbose_name="Minimum Monthly Budget ($)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cleanliness_preference",
            field=models.CharField(
                choices=[
                    ("very_clean", "Very Clean"),
                    ("clean", "Clean"),
                    ("moderate", "Moderate"),
                    ("relaxed", "Relaxed"),
                    ("no_preference", "No Preference"),
                ],
                default="no_preference",
                max_length=20,
                verbose_name="Cleanliness Preference",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Preferred Location/Neighborhood",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="move_in_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Preferred Move-In Date"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pet_preference",
            field=models.CharField(
                choices=[
                    ("no_pets", "No Pets"),
                    ("cats", "Cats"),
                    ("dogs", "Dogs"),
                    ("other", "Other"),
                    ("no_preference", "No Preference"),
                ],
                default="no_preference",
                max_length=20,
                verbose_name="Pet Preference",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="eating_habit",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("no_preference", "No Preference"),
                ],
                default="no_preference",
                max_length=20,
                verbose_name="Eating Preference",
            ),
        ),
        migrations.CreateModel(
            name="ConnectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "favorite_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="profiles.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "favorite_profile")},
            },
        ),
    ]
