# Generated by Django 5.2.7 on 2025-10-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_sharing_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="eating_habit",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("no_preference", "No Preference"),
                ],
                default="no_preference",
                max_length=20,
                verbose_name="Eating Preference",
            ),
        ),
    ]
