# Generated by Django 5.2.7 on 2025-10-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_eating_habit"),
        ("profiles", "0006_profile_budget_max_profile_budget_min_and_more"),
    ]

    operations = []
