# Generated by Django 5.2.7 on 2025-11-21 04:12

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_merge_20251022_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="move_in_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[profiles.models.validate_future_or_today_date],
                verbose_name="Preferred Move-In Date",
            ),
        ),
    ]
