# Generated by Django 5.2.7 on 2025-12-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_merge_20251022_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="university",
            field=models.CharField(
                choices=[
                    ("NYU", "New York University"),
                    ("Columbia", "Columbia University"),
                    ("Fordham", "Fordham University"),
                    ("CUNY", "City University of New York"),
                    ("Pace", "Pace University"),
                ],
                max_length=100,
            ),
        ),
    ]
