# Generated by Django 5.2.7 on 2025-12-04 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(max_length=1000)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="community_covers/"
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public - Anyone can join"),
                            ("private", "Private - Approval required"),
                            (
                                "university",
                                "University - Restricted to specific .edu domain",
                            ),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NYU", "New York University"),
                            ("Columbia", "Columbia University"),
                            ("Fordham", "Fordham University"),
                            ("CUNY", "City University of New York"),
                            ("Pace", "Pace University"),
                            ("The New School", "The New School"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("member_count", models.IntegerField(default=0)),
                ("post_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Communities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("banned", "Banned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_message", models.TextField(blank=True, max_length=500)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="communities.community",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(fields=["slug"], name="communities_slug_81f3ae_idx"),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["privacy"], name="communities_privacy_d54d5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["university"], name="communities_univers_93b3dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["-created_at"], name="communities_created_54da6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymember",
            index=models.Index(
                fields=["community", "status"], name="communities_communi_cbc300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymember",
            index=models.Index(
                fields=["user", "status"], name="communities_user_id_dd6c21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymember",
            index=models.Index(
                fields=["community", "role"], name="communities_communi_5df20f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitymember",
            unique_together={("community", "user")},
        ),
    ]
