# Generated by Django 5.2.7 on 2025-12-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="university",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NYU", "New York University"),
                    ("Columbia", "Columbia University"),
                    ("Fordham", "Fordham University"),
                    ("CUNY", "City University of New York"),
                    ("Pace", "Pace University"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
