# Generated by Django 5.2.7 on 2025-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "communities",
            "0005_event_eventrsvp_event_communities_communi_531107_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="university",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NYU", "New York University"),
                    ("Columbia", "Columbia University"),
                    ("Fordham", "Fordham University"),
                    ("CUNY", "City University of New York"),
                    ("Pace", "Pace University"),
                    ("The New School", "The New School"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
