# Generated by Django 5.2.7 on 2025-10-15 13:19

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="amenities",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="availability_end",
            field=models.DateField(validators=[listings.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name="listing",
            name="availability_start",
            field=models.DateField(validators=[listings.models.validate_future_date]),
        ),
    ]
