# Generated by Django 5.2.7 on 2025-10-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_amenities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="custom_amenities",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
