# Generated by Django 5.2.7 on 2025-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listing_custom_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
