# Generated by Django 5.2.7 on 2025-11-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_is_edited_listing_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
