# Generated by Django 5.2.7 on 2025-12-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_latitude_listing_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="address",
        ),
        migrations.AddField(
            model_name="listing",
            name="city",
            field=models.CharField(default="New York", max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="street_address",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="listing",
            name="zipcode",
            field=models.CharField(default="10012", max_length=10),
        ),
    ]
