# Generated by Django 5.2.7 on 2025-10-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("furniture", "Furniture"),
                    ("electronics", "Electronics"),
                    ("books", "Books"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
