# Generated by Django 5.2.7 on 2025-10-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_item_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="contact_details",
        ),
    ]
