# Generated by Django 5.2.7 on 2025-10-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_remove_item_contact_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="owner_name",
        ),
    ]
