# Generated by Django 5.2.7 on 2025-11-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_remove_item_owner_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
