# Generated by Django 5.2.7 on 2025-11-05 09:13
#
# NOTE: This migration was modified to split pickup_location into three separate fields
# (street_address, city, zipcode) to support map integration and better address handling.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_item_latitude_item_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="pickup_location",
        ),
        migrations.AddField(
            model_name="item",
            name="street_address",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="item",
            name="city",
            field=models.CharField(default="New York", max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="zipcode",
            field=models.CharField(default="10012", max_length=10),
        ),
    ]
