# Generated by Django 5.2.7 on 2025-11-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_item_latitude_item_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="pickup_location",
            new_name="address",
        ),
    ]
