# Generated by Django 5.2.7 on 2025-11-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_rename_pickup_location_item_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="address",
        ),
        migrations.AddField(
            model_name="item",
            name="city",
            field=models.CharField(
                default="New York", help_text="City", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="street_address",
            field=models.CharField(
                default="New York", help_text="Street address", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="zipcode",
            field=models.CharField(
                default="10012", help_text="ZIP/Postal code", max_length=10
            ),
        ),
    ]
