# Generated by Django 5.2.6 on 2025-10-24 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_is_edited_listing_updated_at"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "created_at"], name="messaging_m_thread__1731c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "is_read"], name="messaging_m_thread__01ce92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["listing", "user_a"], name="messaging_t_listing_aa1807_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["listing", "user_b"], name="messaging_t_listing_0e0d67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["updated_at"], name="messaging_t_updated_fc6b0c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_a", models.F("user_b")), _negated=True),
                name="prevent_self_thread",
            ),
        ),
    ]
