# Generated by Django 5.2.7 on 2025-10-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_messaging_m_thread__1731c3_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="chat_messag_thread__9895ae_idx",
            old_name="messaging_m_thread__1731c3_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="chat_messag_thread__af5d24_idx",
            old_name="messaging_m_thread__01ce92_idx",
        ),
        migrations.RenameIndex(
            model_name="thread",
            new_name="chat_thread_listing_e470f4_idx",
            old_name="messaging_t_listing_aa1807_idx",
        ),
        migrations.RenameIndex(
            model_name="thread",
            new_name="chat_thread_listing_5a04ee_idx",
            old_name="messaging_t_listing_0e0d67_idx",
        ),
        migrations.RenameIndex(
            model_name="thread",
            new_name="chat_thread_updated_119593_idx",
            old_name="messaging_t_updated_fc6b0c_idx",
        ),
    ]
