# Generated by Django 5.2.7 on 2025-10-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_messaging_m_thread__1731c3_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="message",
            table="messaging_message",
        ),
        migrations.AlterModelTable(
            name="thread",
            table="messaging_thread",
        ),
    ]
