# Generated by Django 5.2.7 on 2025-10-29 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_is_edited_listing_updated_at"),
        ("marketplace", "0002_item_category"),
        ("messaging", "0002_message_messaging_m_thread__1731c3_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="marketplace.item",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="listings.listing",
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["item", "user_a"], name="messaging_t_item_id_70a239_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["item", "user_b"], name="messaging_t_item_id_cf0697_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.UniqueConstraint(
                fields=("item", "user_a", "user_b"), name="unique_thread_per_item_pair"
            ),
        ),
    ]
