# Generated by Django 5.2.7 on 2025-12-14 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_remove_listing_address_listing_city_and_more"),
        ("marketplace", "0006_rename_pickup_location_item_address"),
        ("messaging", "0003_thread_item_alter_thread_listing_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item__isnull", True), ("listing__isnull", True)),
                fields=("user_a", "user_b"),
                name="unique_thread_per_roommate_pair",
            ),
        ),
    ]
