# Listings Constants
# This file contains all listings-related constants to be used across the codebase

# Amenity Choices
# Format: (value, display_name)
AMENITY_CHOICES = [
    ("furnished", "Furnished"),
    ("utilities", "Utilities Included"),
    ("wifi", "WiFi"),
    ("laundry", "Laundry"),
    ("elevator", "Elevator"),
    ("pets", "Pets Allowed"),
    ("ac", "Air Conditioning"),
]

# NYC Neighborhood to Borough Mapping
# Maps Manhattan neighborhoods and common aliases to help with location searches
NYC_NEIGHBORHOOD_BOROUGH_MAP = {
    # Manhattan neighborhoods
    "manhattan": [
        "manhattan",
        "upper east side",
        "upper west side",
        "midtown",
        "midtown east",
        "midtown west",
        "chelsea",
        "gramercy",
        "flatiron",
        "union square",
        "east village",
        "west village",
        "greenwich village",
        "soho",
        "tribeca",
        "lower east side",
        "chinatown",
        "little italy",
        "nolita",
        "financial district",
        "battery park city",
        "harlem",
        "east harlem",
        "spanish harlem",
        "morningside heights",
        "washington heights",
        "inwood",
        "murray hill",
        "kips bay",
        "stuyvesant town",
        "peter cooper village",
        "alphabet city",
        "noho",
        "bowery",
    ],
    # Brooklyn neighborhoods
    "brooklyn": [
        "brooklyn",
        "williamsburg",
        "greenpoint",
        "bushwick",
        "bed-stuy",
        "bedford-stuyvesant",
        "park slope",
        "prospect heights",
        "crown heights",
        "fort greene",
        "clinton hill",
        "dumbo",
        "brooklyn heights",
        "downtown brooklyn",
        "boerum hill",
        "cobble hill",
        "carroll gardens",
        "red hook",
        "sunset park",
        "bay ridge",
        "bensonhurst",
        "coney island",
        "brighton beach",
        "sheepshead bay",
        "flatbush",
        "midwood",
        "canarsie",
        "brownsville",
        "east new york",
    ],
    # Queens neighborhoods
    "queens": [
        "queens",
        "astoria",
        "long island city",
        "lic",
        "sunnyside",
        "woodside",
        "jackson heights",
        "elmhurst",
        "corona",
        "flushing",
        "forest hills",
        "rego park",
        "kew gardens",
        "jamaica",
        "ridgewood",
        "glendale",
        "middle village",
        "maspeth",
        "bayside",
        "whitestone",
        "college point",
    ],
    # Bronx neighborhoods
    "bronx": [
        "bronx",
        "the bronx",
        "riverdale",
        "kingsbridge",
        "fordham",
        "morris heights",
        "tremont",
        "concourse",
        "mott haven",
        "hunts point",
        "soundview",
        "parkchester",
        "co-op city",
        "pelham bay",
        "throgs neck",
    ],
    # Staten Island neighborhoods
    "staten island": [
        "staten island",
        "st. george",
        "tompkinsville",
        "stapleton",
        "port richmond",
        "new brighton",
        "west brighton",
        "todt hill",
        "great kills",
        "tottenville",
    ],
}
